### ISSUE TITLE
!r give command

### ISSUE THREAD

**Issue by y0sh1DE** [y0sh1DE/comiebot#15]
We need a command to give others players money, without me having to tweak stuff within the database. kkthxbb

**Comment by y0sh1DE** [comment]
Added first draft in 211499facb302e2c134491cffbb61933ccb0644f

**Comment by KnuTNatioN** [comment]
fixed last typos in draft

**Comment by y0sh1DE** [comment]
Finally added in 4717ea967f2c6a0c27ff463e1a283e8bf10eda35
