### ISSUE TITLE
Comie Bot couldn't find new random Picture's

### ISSUE THREAD

**Issue by wernerlat** [y0sh1DE/comiebot#23]

**Comment by y0sh1DE** [comment]
When using !img, comie says that it couldnt find a new image after 100 tries

**Comment by KnuTNatioN** [comment]
There is no problem with this state.
(i made a git copy)
my DB: 5.5.5-10.3.22-MariaDB

**Comment by KnuTNatioN** [comment]
No problem with code
Problem is rather with the operator server / database (connection).

Sorry for Closing...

**Comment by y0sh1DE** [comment]
Restarting the python script fixed it for now. Maybe™ gonna investigate in the future.
