### ISSUE TITLE
no check for unique Anime title

### ISSUE THREAD

**Issue by KnuTNatioN** [y0sh1DE/comiebot#26]
3 times add "specific anime Title" like:
!a awesome anime https://link-to-anime.tld/a=awesome-anime tag1, tag2, randomtag
!a awesome anime https://link-to-anime.tld/a=awesome-anime tag1, tag2, randomtag
!a awesome anime https://link-to-anime.tld/a=awesome-anime tag1, tag2, randomtag

Added 3x the anime.

**Comment by KnuTNatioN** [comment]
*unique

**Comment by y0sh1DE** [comment]
Fixed this in latest commit
